openapi: 3.0.3
info:
  title: Private Analytics API
  description: |-
    OpenAPI 3.0 Specification of Mapp Intelligence Private AnalyticsAPI 

    In order to use these endpoints you must authorize by using a valid OAuth clientID configured in Mapp Intelligence Settings section.
    
    This API can be solelly used within Mapp Network.
  version: 1.0.0
  contact:
    name: Technical Support Mapp Digital
    url: https://mapp.com/tech-support/
servers:
  - url: https://intelligence-dev-private.nbg.webtrekk.com/analytics/api
    description: DEV
  - url: https://intelligence-int-private.nbg.webtrekk.com/analytics/api
    description: INT
  - url: https://intelligence-qa-private.nbg.webtrekk.com/analytics/api
    description: QA
  - url: https://intelligence.nbg.webtrekk.com/analytics/api
    description: PROD
tags:
  - name: Analysis
    description: Submit analysis and get data
  - name: Available Objects
    description: Get informations about available objects you can use to build Analysis
components:
  securitySchemes:
    oauth_security_scheme:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /analytics/api/oauth/token
          scopes:
            mapp.intelligence-api.private: Use intelligence APIs for internal usage
  schemas:
    FilterPredicateEnum:
      type: string
      description: Filter predicates
      enum:
        - EQUAL
        - UNEQUAL
        - LESS
        - LESSEQUAL
        - GREATER
        - GREATEREQUAL
        - BETWEEN
        - LIKE
        - NOT_LIKE
    ConnectorPredicateEnum:
      type: string
      description: Connectors
      enum:
        - AND
        - OR
    InOrNotInPredicateEnum:
      type: string
      enum:
        - IN
        - NOT_IN
    ContextEnum:
      type: string
      description: Context to evaluate the metric/dimension. If context property is not given or empty the default context of the object will be used. The default context can be identified from the context property in the response list of /query-objects.
      enum:
        - VISITOR
        - SESSION
        - PAGE
        - ACTION
        - ATOMIC
        - NONE
    ScopeEnum:
      type: string
      enum:
        - OBJECT
        - NONE
    ColumnPeriodEnum:
      type: string
      description: 'Indicates which Time range must be used for the column. ANALYSIS: uses the analysis time range. COLUMN: uses the time filter defined inside the column. ELEMENT: uses the time filter defined inside the element configuration - i.e. custom metric/formula'
      enum:
        - ANALYSIS
        - COLUMN
        - ELEMENT
    SortDirectionEnum:
      type: string
      description: Possible sorting directions
      enum:
        - ASCENDING
        - DESCENDING
    Filter:
      type: object
      properties:
        name:
          type: string
          description: Name of the Metric or Dimension being filtered.
        filterPredicate:
          $ref: '#/components/schemas/FilterPredicateEnum'
        connector:
          $ref: '#/components/schemas/ConnectorPredicateEnum'
        caseSensitive:
          type: boolean
        context:
          $ref: '#/components/schemas/ContextEnum'
        intern:
          type: boolean
          description: Indicates if filter should be prioritized (Advanced).
          default: false
        value1:
          type: string
        value2:
          type: string
    Container:
      type: object
      properties:
        filters:
          type: array
          description: Array of filters
          items:
            $ref: '#/components/schemas/Filter'
        containers:
          type: array
          description: array of containers (recursion)
          items:
            $ref: '#/components/schemas/Container'
        connector:
          $ref: '#/components/schemas/ConnectorPredicateEnum'
        context:
          $ref: '#/components/schemas/ContextEnum'
        type:
          description: Indicates how filters must be applied. TIME_ORDER is sequential, NORMAL not
          type: string
          enum:
            - NORMAL
            - TIME_ORDER
        inOrNotIn:
          $ref: '#/components/schemas/InOrNotInPredicateEnum'
    KpiQuery:
      type: object
      description: KPI query definition
      properties:
        elementPeriod:
          type: string
          description: |-
            One of the following periods should be used:
            * ELEMENT: when the time filter is either inherited from the report or the time filter configured in the report element configuration.
            * MONAD: when the time filter is inherited from the custom metric configuration.
          enum:
            - ELEMENT
            - MONAD
        type:
          type: string
          description: Type of the query
          enum:
            - KPI
            - SPARKLINE
        metricName:
          type: string
          description: name of the metric of the KPI
        dimensionName:
          type: string
          description: name of the dimension of the KPI
        comparison:
          $ref: '#/components/schemas/Comparison'
        predefinedContainer:
          $ref: '#/components/schemas/Container'
        predefinedSegmentConnections:
          type: array
          items:
            $ref: '#/components/schemas/Filter'
    TableQuery:
      type: object
      description: Tabular query definition
      properties:
        columns:
          type: array
          description: Array of columns
          items:
            type: object
            properties:
              name:
                type: string
              sortDirection:
                $ref: '#/components/schemas/SortDirectionEnum'
              sortIndex:
                type: integer
                description: Indicates order of sorting when there is more than one sorting column. (starting from 0).
              lowerLimit:
                type: integer
              upperLimit:
                type: integer
              inTimeSeries:
                type: boolean
                description: Optional property indicating if a column will be used in time series view mode; defaults to false. Can be omitted if it's value is not set to true.
              columnPeriod:
                $ref: '#/components/schemas/ColumnPeriodEnum'
              scope:
                $ref: '#/components/schemas/ScopeEnum'
              context:
                $ref: '#/components/schemas/ContextEnum'
              predefinedContainer:
                $ref: '#/components/schemas/Container'
        variant:
          type: string
          description: Type of Data Structure
          enum:
            - LIST
            - PIVOT
            - PIVOT_AS_LIST
            - COMPARISON
        predefinedContainer:
          $ref: '#/components/schemas/Container'
        predefinedSegmentConnections:
          type: array
          items:
            $ref: '#/components/schemas/Filter'
        viewMode:
          $ref: '#/components/schemas/ViewMode'
      required:
        - columns
        - variant
        - predefinedContainer
    ViewMode:
      type: object
      properties:
        active:
          type: string
          enum:
            - comparison
            - timeSeries
        comparison:
          type: object
          properties:
            type:
              type: string
              description: type of comparison. It can be either on *time* or *segment*. The corresponding properties
                must be filled accordingly in *values* and *sorting*
              enum:
                - time
                - segment
            values:
              type: object
              properties:
                time:
                  type: array
                  items:
                    $ref: '#/components/schemas/Filter'
                segment:
                  type: array
                  items:
                    $ref: '#/components/schemas/SegmentContainer'
            sorting:
              type: object
              properties:
                time:
                  type: array
                  items:
                    $ref: '#/components/schemas/ViewModeComparisonSortingItem'
                segment:
                  type: array
                  items:
                    $ref: '#/components/schemas/ViewModeComparisonSortingItem'
        timeSeries:
          type: object
          properties:
            timeName:
              type: string
              description: The name of the time dimension used in the time series - i.e. "time_days" for days.
            viewType:
              type: string
              description: The type of the time series view mode. Set "top" for time series of the top "x" number of objects. Set "values" based on specific object values populated in the values list of this configuration.
              enum:
                - top
                - values
            top:
              type: integer
              description: The number of top objects the time series is build upon.
            values:
              type: array
              description: A list of object values - i.e. ["Seach", "Cart", "Home"] for object "pages".
              items:
                type: string
    ViewModeComparisonSortingItem:
      type: object
      description: Sorting of comparison
      properties:
        alias:
          type: string
          description: alias of the column being sorted
        direction:
          $ref: '#/components/schemas/SortDirectionEnum'
    SegmentContainer:
      type: object
      properties:
        segmentID:
          type: string
          description: ID of the Segment
        connectorPredicate:
          type: string
        inOrNotInPredicate:
          type: string
        context:
          $ref: '#/components/schemas/ContextEnum'
        position:
          type: integer
          description: Indicates segment ordering in case of several Segment
    Comparison:
      type: object
      description: Comparison definition
      properties:
        type:
          type: string
          description: Type of comparison
          enum:
            - NONE
            - PERIOD
            - LIMIT
            - SLIDING_WINDOW
        slidingWindowWeekdayAdjust:
          type: boolean
        slidingWindowTimeShift:
          type: string
          enum:
            - PRECEDING
            - PREVIOUS_MONTH
            - PREVIOUS_QUARTER
            - PREVIOUS_YEAR
        filter:
          $ref: '#/components/schemas/Filter'
    AnalysisQuery:
      type: object
      description: Defintiona of a anaylsis query structure
      properties:
        resultType:
          type: string
          description: Type of result
          enum:
            - DATA_ONLY
        queryObject:
          description: Different type of queries are possible
          oneOf:
            - $ref: '#/components/schemas/TableQuery'
            - $ref: '#/components/schemas/KpiQuery'
      required:
        - resultType
        - queryObject
    AnalysisResult:
      type: object
      properties:
        calculationDataType:
          type: string
          description: DataType returned
          enum:
            - RAW_DATA
            - RAW_DATA_SAMPLING
        rows:
          type: array
          description: Array of rows
          items:
            type: array
            description: Array of values following the strict order of the headers
            items: {}
        rowCount:
          type: integer
          description: Number of rows returned.
        rowCountTotal:
          type: integer
          description: Number of rows in the whole resultSet wihtout subtotals
        headers:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the Dimension or Metric
              alias:
                type: string
                description: Generated unique identifier of the column in the analysis.
              arrangeType:
                type: string
                description: Mapp identifier of the Dimension or Metric
              metric:
                type: boolean
                description: Indicates if column is a metric
              dimension:
                type: boolean
                description: Indicates if column is a dimension
              sumPositions:
                type: array
                description: Indicates which rows contains a (sub)total value
                items:
                  type: integer
              pivotGroups:
                type: array
                description: Indicates which rows contains a grouping row
                items:
                  type: integer
              sortIndex:
                type: integer
                description: Indicates order of sorting when there is more than one sorting column. (starting from 0)
              sortDirection:
                $ref: '#/components/schemas/SortDirectionEnum'
        columnCount:
          type: integer
          description: Number of columns
        warnings:
          type: array
          description: Array of warnings occurred during calculation
          items:
            $ref: '#/components/schemas/Warning'
        timerange:
          type: array
          description: time range boundaries with format yyyy-MM-dd HH:mm:ss
          minItems: 2
          maxItems: 2
          items:
            type: string
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the calculation
    Warning:
      type: object
      properties:
        name:
          type: string
          description: |-
            Each warnings has specific properties described in following table:
            | Warning| Description | Relevant parameters |
            | ---------------- | ------------| -----------------------------------|
            | FilterLogicalCubeMismatch | At least one filter is ignored due to incompatibily with Dimensions and Metrics used. | List of incomptible filter objects in _names_ array. |
            | InvalidMetricContext | Metric used in an invalid context. | List of metric with invalid context in _aliases_ array. |
            | SortingEnforced |  Sorting criteria has been added automatically | List of objects that were sorted automatically in _aliases_ array. |
            | NoSortingDefined |  Sorting criteria is required for some dimensions. | List of dimensions requiring a sorting in _names_ array. |
            | SortingLimitExceeded | 3 sorting criteria are allowed. All additional sorting criteria have been omitted.| List of columns ignored for sorting in _aliases_ array. |
            | SortingRemoved | A requested sorting criteria has been removed | List of objects that were removed automatically in _aliases_ array. |
            | TodayRemoved | Today date has been removed from calculation time range because the selected datasource does not contain it. | daysInDataSource, todayDate|
          enum:
            - FilterLogicalCubeMismatch
            - InvalidMetricContext
            - SortingEnforced
            - NoSortingDefined
            - SortingLimitExceeded
            - SortingRemoved
            - TodayRemoved
        parameters:
          type: object
          properties:
            arrangeTypes:
              type: array
              description: List of internal object names (dimension, metrics, filter, ...) that corresponds to the warning.
              items:
                type: string
            aliases:
              type: array
              description: List of columns aliases that corresponds to the error. See Result Header alias property.
              items:
                type: string
            names:
              type: array
              description: List of object names (dimension, metrics, filter, ...) that corresponds to the warning.
              items:
                type: string
            daysInDataSource:
              type: string
              description: Number of days in the datasource which is beeing cut
            todayDate:
              type: string
              description: Date of the day being cut
    Error:
      type: object
      properties:
        name:
          type: string
          description: |-
            Each error has specific properties described in following table:
            | Error| Description | Relevant parameters |
            | ---------------- | ------------| -----------------------------------|
            | UnmappedName | At least one object name cannot be found. | List of objects not found in _names_ array. |
            | PivotIncompatibleMetric | Metric not usable in Pivot detected.| List of incompatible Metrics in _names_ array. |
            | PivotIncompatibleDimension |Dimension not usable in Pivot detected. | List of incompatible Dimensions in _names_ array. |
            | AnalysisLogicalCubeMismatch | All Dimensions and Metrics are not compatible. | List of incompatible objects in _names_ array. |
            | InvalidSortingCriteria | Sorting is applied on a non-sortable object.| List of invalid sorted objects in _names_ array. |
          enum:
            - UnmappedName
            - PivotIncompatibleMetric
            - PivotIncompatibleDimension
            - AnalysisLogicalCubeMismatch
            - InvalidSortingCriteria
        parameters:
          type: object
          properties:
            arrangeTypes:
              type: array
              description: List of internal object names (dimension, metrics, filter, ...) that corresponds to the error.
              items:
                type: string
            aliases:
              type: array
              description: List of columns aliases that corresponds to the error. See Result Header alias property.
              items:
                type: string
            names:
              type: array
              description: List of object names (dimension, metrics, filter, ...) that corresponds to the error.
              items:
                type: string
    Problem:
      type: object
      properties:
        status:
          type: integer
          description: HTTP Status Code
        statusCode:
          type: string
          description: Specific Mapp Error Code
        title:
          type: string
          description: Short description of the problem
        detail:
          type: string
          description: Detailed informations about the problem
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/Warning'
    QueryState:
      title: QueryState
      type: object
      properties:
        calculationId:
          type: string
          description: Id of the calculated data
        resultUrl:
          type: string
          description: Link to get analysis data
        status:
          type: string
          description: Analysis query state
          enum:
            - SUCCESS
            - FAILED
            - ABORTED
            - RUNNING
            - INITIATED
        details:
          type: object
          properties:
            lastUpdatedAt:
              type: number
              description: 'Last update time in milliseconds since the UNIX epoch'
    DataTypeEnum:
      type: string
      description: Type of data
      enum:
        - STRING
        - NUMBER
        - GENERIC
    DisplayTypeEnum:
      type: string
      description: Indicate how the data should be displayed
      enum:
        - NORMAL
        - TIME
        - CURRENCY
        - DISTRIBUTION
        - COMPARE
    ElementTypeEnum:
      type: string
      description: Type of element
      enum:
        - CAMPAIGNS_ATTRIBUTION
        - CUSTOM_CATEGORY
        - CUSTOM_FORMULA
        - CUSTOM_METRIC
        - CUSTOM_PARAMETER
        - CUSTOM_PROCESS
        - CUSTOM_SOURCE
        - CUSTOM_VISITOR_GROUPS_TRAFFIC
        - CUSTOM_WEBSITE_GOALS
        - DEFAULT_DIMENSION
        - DEFAULT_METRIC
        - PREDEFINED_FORMULA
        - PREDEFINED_METRIC
    Metric:
      title: Metric
      type: object
      description: Description of a metric
      properties:
        name:
          type: string
          description: API name of the metric
        dataType:
          $ref: '#/components/schemas/DataTypeEnum'
        title:
          type: string
          description: Human readable name of the metric. Localized
        elementType:
          $ref: '#/components/schemas/ElementTypeEnum'
        metricDisplayType:
          $ref: '#/components/schemas/DisplayTypeEnum'
        context:
          $ref: '#/components/schemas/ContextEnum'
        sortable:
          type: boolean
          description: Indicates if object can be sorted.
      required:
        - name
        - dataType
        - title
        - elementType
        - metricDisplayType
    Dimension:
      title: Dimension
      type: object
      description: Description of a Dimension element
      properties:
        name:
          type: string
          description: API name of the dimension
        dataType:
          $ref: '#/components/schemas/DataTypeEnum'
        title:
          type: string
          description: Human readable name of the metric. Localized
        elementType:
          $ref: '#/components/schemas/ElementTypeEnum'
        context:
          $ref: '#/components/schemas/ContextEnum'
        mapping:
          type: object
          description: Optional list of Mapping values
          additionalProperties:
            type: string
        timeFormatPattern:
          description: Standard datetime pattern. Indicates that current STRING represents a Date
          type: string
        sortable:
          type: boolean
          description: Indicates if object can be sorted.
      required:
        - name
        - dataType
        - title
        - elementType
    QueryObjects:
      title: QueryObjects
      type: object
      properties:
        metrics:
          type: array
          description: List of available metrics
          items:
            $ref: '#/components/schemas/Metric'
        dimensions:
          type: array
          description: List of available dimensions
          items:
            $ref: '#/components/schemas/Dimension'
      required:
        - metrics
        - dimensions
    SegmentDefinition:
      title: SegmentDefinition
      description: User segment
      type: object
      properties:
        id:
          type: integer
          description: ID of the segment to be used in analysis
        title:
          type: string
          description: Name of the segment
        description:
          type: string
          description: Description of the segment
      required:
        - id
        - title
        - description
    DynamicTimeFilterDefinition:
      title: DynamicTimeFilterDefinition
      description: Dynamic Time Filter
      type: object
      properties:
        title:
          type: string
          description: Human readable description of the dynamic time filter (localized)
        name:
          type: string
          description: API name of the filter value
        dynamicFilter:
          type: object
          description: Snippet code which can be used in analysis
          properties:
            name:
              type: string
              description: API Name of the filtered dimension
            filterPredicate:
              $ref: '#/components/schemas/FilterPredicateEnum'
            connector:
              $ref: '#/components/schemas/ConnectorPredicateEnum'
            context:
              $ref: '#/components/schemas/ContextEnum'
            value1:
              type: string
              description: Value to be filtered on.
            value2:
              type: string
              description: Second value to be filtered on. Only relevant for BETWEEN.
          required:
            - name
            - connector
            - filterPredicate
            - value1
            - value2
            - context
      required:
        - title
        - name
        - dynamicFilter
    AnalysisUsage:
      title: AnalysisUsage
      description: Analysis Usage for a given period
      type: object
      properties:
        calculationsCount:
          type: integer
          description: Number of calculation for the current period
        maxCalculationsAllowed:
          type: integer
          description: Max number of allowed of calculation per Month as defined in contract
        month:
          type: integer
          description: month of the current period
        year:
          type: integer
          description: Year of the current period
      required:
        - calculationsCount
        - maxCalculationsAllowed
        - month
        - year
  responses:
    Forbidden:
      description: No permission to execute operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            AnalysisNotFound:
              summary: Invalid Token
              value:
                title: Invalid Token
                status: 403
                detail: Token not valid
                statusCode: INVALID_TOKEN
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Problem'
          examples:
            AnalysisNotFound:
              summary: CorrelationId does not exist
              value:
                title: Analysis not found
                status: 404
                detail: Analysis not found
                statusCode: ANALYSIS_NOT_FOUND
security:
  - oauth_security_scheme:
      - mapp.intelligence-api
paths:
  /analysis-query:
    post:
      tags:
        - Analysis
      summary: Create calculation query
      description: |-
        Create a calculation query. 

         Response will be either 
        + 200 if the result is already available and can be retrieved by using the provided link (or calculationId) 
        + 201 if the calculation is being queued. Status can be polled by using the provided link (or correlationId).
      externalDocs:
        url: https://documentation.mapp.com
      requestBody:
        description: Analytics Request Format
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisQuery'
            examples:
              Pivot:
                $ref: ../examples/example-analysis-query-pivot.json
              Comparison:
                $ref: ../examples/example-analysis-query-comparison.json
              TimeSeries:
                $ref: ../examples/example-analysis-query-time-series.json
      parameters:
        - name: accountId
          in: query
          description: Id of the account where the query must be executed
          required: true
          schema:
            type: string
        - name: userId
          in: query
          description: Id of the user with which the query must be executed (User Filter etc...)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Analysis completed
          content:
            application/json:
              schema:
                properties:
                  calculationId:
                    type: string
                  resultUrl:
                    type: string
              examples:
                Calculated data available:
                  value:
                    calculationId: 8612fa1eaada53fbb1956402bbded4db732074e7e399645880ae6a54b99a2bd9_294915650484552
                    resultUrl: https://intelligence.eu.mapp.com/analytics/api/analysis-result/8612fa1eaada53fbb1956402bbded4db732074e7e399645880ae6a54b99a2bd9_294915650484552
        '201':
          description: Analysis enqueued
          content:
            application/json:
              schema:
                properties:
                  correlationId:
                    type: string
                  statusUrl:
                    type: string
              examples:
                Query enqueued:
                  value:
                    correlationId: 94295cef-5b64-4934-ba25-011dd997aa81
                    statusUrl: https://intelligence.eu.mapp.com/analytics/api/analysis-query/94295cef-5b64-4934-ba25-011dd997aa81
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          description: Invalid JSON input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /analysis-query/{correlationId}:
    get:
      tags:
        - Analysis
      summary: Get query status
      description: |-
        Returns status of the analysis query. 

         Once calculation is SUCCESS, result is  available and can be retrieved by using the provided link (or calculationId).
      externalDocs:
        url: https://documentation.mapp.com
      parameters:
        - name: correlationId
          in: path
          description: ID of the query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Query status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryState'
              examples:
                Analysis running:
                  value:
                    calculationId: 579d66fe984f72f7154c5f48e0d3d65741dac870eb337a0524d4d3db02f119b7_294915650484552
                    status: RUNNING
                    details:
                      lastUpdatedAt: 1630430823529
                Analysis completed:
                  value:
                    calculationId: 579d66fe984f72f7154c5f48e0d3d65741dac870eb337a0524d4d3db02f119b7_294915650484552
                    status: SUCCESS
                    resultUrl: https://intelligence.eu.mapp.com/analytics/api/analysis-result/579d66fe984f72f7154c5f48e0d3d65741dac870eb337a0524d4d3db02f119b7_294915650484552
                    details:
                      lastUpdatedAt: 1630430828912
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Analysis
      summary: Cancel query
      description: Abort running query, if still running
      externalDocs:
        url: https://documentation.mapp.com
      parameters:
        - name: correlationId
          in: path
          description: ID of the query to be canceled
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Query successfully canceled
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /analysis-result/{calculationId}:
    get:
      tags:
        - Analysis
      summary: Get analysis result
      description: Retrieve the analysis data.
      externalDocs:
        url: https://documentation.mapp.com
      parameters:
        - name: calculationId
          in: path
          description: ID of the calculated Data
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResult'
              examples:
                Simple analysis result:
                  $ref: ../examples/example-analysis-result.json
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /analysis-usage/current:
    get:
      tags:
        - Analysis
      summary: Get number of analysis done for current month
      description: Get number of analysis done for current month
      externalDocs:
        url: https://documentation.mapp.com
      parameters:
        - name: accountId
          in: query
          description: Id of the account whose the analysis usage is requested
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisUsage'
              examples:
                AnalysisUsage:
                  value:
                    calculationsCount: 4012
                    maxCalculationsAllowed: 310000
                    month: 1
                    year: 2022
        '403':
          $ref: '#/components/responses/Forbidden'
  /query-objects:
    get:
      tags:
        - Available Objects
      summary: List all available dimensions and metrics
      description: List all available dimensions and metrics
      externalDocs:
        url: https://documentation.mapp.com
      parameters:
        - name: language
          in: query
          description: |-
            Optional standard ISO-639-1 language code for translation (when applicable).

            Only "de" and "en" supported for the moment. 

            Default is  "en"
          required: false
          schema:
            type: string
        - name: accountId
          in: query
          description: Id of the account whose the query objects are requested
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryObjects'
              examples:
                Query Objects:
                  $ref: ../examples/query-objects.json
        '403':
          $ref: '#/components/responses/Forbidden'
  /segments:
    get:
      tags:
        - Available Objects
      summary: List all available segments
      description: List all available segments
      externalDocs:
        url: https://documentation.mapp.com
      parameters:
        - name: accountId
          in: query
          description: Id of the account whose segments are requested
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentDefinition'
              examples:
                Segments:
                  value:
                    - id: 67
                      title: Social media Visitor
                      description: Visitor which came from Social Media
                    - id: 95
                      title: Returning Visitor
                      description: User with at least 5 Visits
        '403':
          $ref: '#/components/responses/Forbidden'
  /dynamic-timefilters:
    get:
      tags:
        - Available Objects
      summary: List all available dynamic timefilters
      description: List all available dynamic timefilter value.
      externalDocs:
        url: https://documentation.mapp.com
      parameters:
        - name: language
          in: query
          description: |-
            Optional standard ISO-639-1 language code for translation (when applicable).

            Only "de" and "en" supported for the moment. 

            Default is  "en"
          required: false
          schema:
            type: string
        - name: accountId
          in: query
          description: Id of the account whose the dynamic time filters are requested
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicTimeFilterDefinition'
              examples:
                DynamicTimeFilters:
                  value:
                    - title: Today
                      name: today
                      dynamicFilter:
                        name: time_dynamic
                        connector: AND
                        filterPredicate: LIKE
                        value1: today
                        value2: ''
                        context: NONE
                    - title: Today, 7 days ago
                      name: before_7_days
                      dynamicFilter:
                        name: time_dynamic
                        connector: AND
                        filterPredicate: LIKE
                        value1: before_7_days
                        value2: ''
                        context: NONE
                    - title: Today, 14 days ago
                      name: before_14_days
                      dynamicFilter:
                        name: time_dynamic
                        connector: AND
                        filterPredicate: LIKE
                        value1: before_14_days
                        value2: ''
                        context: NONE
        '403':
          $ref: '#/components/responses/Forbidden'